---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql
spec:
      volumes:
        - name: mysql-storage
          hostPath:
              path: /home/sql
      nodeSelector:
        app:  mysql
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: "p"
            - name: MYSQL_USER
              value: priyanshu
            - name: MYSQL_PASSWORD
              value: root         
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql


